### ISSUE TITLE
Port-forward to pods not available

### ISSUE THREAD

**Issue by allemp** [hcavarsan/kftray#260]
**Describe the bug**

Issue #23 mentions that it should be possible to port-forward to pods, but only service and proxy are available in the workload type list

**Expected behavior**

I expected to be able to select pods as a workload type to to select the pod I want to forward.

**Desktop (please complete the following information):**
 - MacOS Sonoma 14.5

**Additional context**

If it was not intentional to allow port-forwarding to pods or I missed something then disregard.

Thanks!

**Comment by hcavarsan** [comment]
hey @allemp ,

i've thought about this and didn't implement port-forward directly to pods because if it's a specific pod name, the config will only be valid while the pod is running. once the pod is terminated, the config in kftray would stop working.

but i get that today you need a service created for port-forward to work, and this doesn't cover some cases.

what i'm thinking is to have a workload_type pod and instead of selecting the pod name, select a pod label for port-forward.

do you think this would work?

**Comment by allemp** [comment]
Hello! I think that would work just fine!
